#!/usr/bin/env ruby

require 'rubygems'
require 'commander/import'
require 'milk'

program :version, Milk::VERSION
program :description, 'Build utility for the Milk framework'

command :build do |c|
  c.syntax = 'milk build [options]'
  c.summary = ''
  c.description = ''
  c.example 'description', 'command example'
  c.option '--some-switch', 'Some switch that does something'
  c.action do |args, options|
    # Do something or c.when_called Milk::Commands::Build
  end
end
